#!/bin/bash
# Mobile optimization patterns to apply to all location content files
# This is a reference file showing what patterns were applied

echo "Mobile Optimization Patterns Applied:"
echo "1. Hero: pt-20 pb-16 → pt-12 pb-10 sm:pt-20 sm:pb-16"
echo "2. Hero gap: gap-12 → gap-8 sm:gap-12"
echo "3. Badge: px-4 text-sm → px-3 text-xs sm:px-4 sm:text-sm"
echo "4. H1: text-4xl → text-3xl sm:text-5xl"
echo "5. Description: text-lg/text-xl → text-sm/text-base sm:text-lg/sm:text-xl"
echo "6. Button: px-8 py-4 text-lg → px-5 py-3 sm:px-8 sm:py-4 text-sm sm:text-lg"
echo "7. Icons: h-5 w-5 → h-4 w-4 sm:h-5 sm:w-5"
echo "8. Button spans: Add hidden sm:inline for desktop, sm:hidden for mobile"
echo "9. Image: h-[400px]/h-[500px] → h-[280px] sm:h-[400px] lg:h-[500px]"
echo "10. Sections: py-20 → py-10 sm:py-16 lg:py-20"
echo "11. H2: text-3xl/text-4xl → text-2xl sm:text-4xl lg:text-5xl"
echo "12. Cards gap: gap-8 → gap-4 sm:gap-6 lg:gap-10"
echo "13. Cards: rounded-2xl p-8 → rounded-xl sm:rounded-2xl p-4 sm:p-6"
echo "14. Card icons: w-8 h-8 → w-6 h-6 sm:w-8 sm:h-8"
echo "15. Card titles: text-xl → text-base sm:text-xl"
echo "16. Card desc: add text-sm sm:text-base"
echo "17. Brands section: py-20 → py-10 sm:py-16"
echo "18. Brands H2: text-3xl → text-xl sm:text-3xl"
echo "19. Brand images: h-20 w-32 → h-14 w-20 sm:h-20 sm:w-28"
echo "20. FAQ accordion: space-y-4 → space-y-2 sm:space-y-4"
echo "21. FAQ items: px-6 → px-4 sm:px-6"
echo "22. FAQ trigger: py-6 → text-sm sm:text-base lg:text-lg py-3 sm:py-4"
echo "23. FAQ content: pb-6 → text-xs sm:text-sm lg:text-base pb-3 sm:pb-4"

echo ""
echo "Files optimized:"
echo "✓ ChinoHillsContent.tsx"
echo "✓ ClaremontContent.tsx"
echo "... continuing with remaining files"
